In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

from dirrac.data.preprocess_data import GermanCredit, SBA, Student
from mace.loadModel import loadModelForDataset
from dirrac.classifier.logistic import logistic_classifier
from dirrac.gen_counterfactual import DRRA
from ar.gen_counterfactual import LinearAR
from mace.batchTest import runExperiments

[ENV WARNING] deactivate virtualenv to allow for testing Actionable Recourse


In [3]:
model_trained, X_train, y_train, X_test, y_test, X_shift, y_shift = loadModelForDataset('lr', 'german')

In [4]:
X_train.shape, y_train.shape, X_test, y_test.shape

((480, 8),
 (480,),
 array([[0.29411765, 0.0955761 , 0.66666667, 0.03571429, 0.        ,
         1.        , 0.        , 0.        ],
        [0.05882353, 0.17321448, 0.66666667, 0.35714286, 0.        ,
         1.        , 0.        , 0.        ],
        [0.38235294, 0.39809618, 0.33333333, 0.60714286, 1.        ,
         0.        , 0.        , 0.        ],
        [0.07352941, 0.06448773, 0.66666667, 0.14285714, 0.        ,
         1.        , 0.        , 0.        ],
        [0.29411765, 0.0655882 , 0.33333333, 0.07142857, 0.        ,
         1.        , 0.        , 0.        ],
        [0.29411765, 0.1455926 , 0.66666667, 0.17857143, 0.        ,
         0.        , 1.        , 0.        ],
        [0.64705882, 0.55282271, 0.66666667, 0.35714286, 0.        ,
         1.        , 0.        , 0.        ],
        [0.02941176, 0.23995818, 0.33333333, 0.23214286, 1.        ,
         0.        , 0.        , 0.        ],
        [0.82352941, 0.3944096 , 0.66666667, 0.14285714, 0. 

In [5]:
model_trained.coef_, model_trained.intercept_

(array([[-1.35294452, -0.4826626 ,  0.39909664,  0.853531  ,  1.11028091,
         -0.67962095, -0.40275798, -0.03171284]]),
 array([-0.01895876]))

In [6]:
model_trained.predict_proba(X_test)

array([[0.69974585, 0.30025415],
       [0.57220958, 0.42779042],
       [0.26247945, 0.73752055],
       [0.60854238, 0.39145762],
       [0.71791907, 0.28208093],
       [0.61572288, 0.38427712],
       [0.78073322, 0.21926678],
       [0.2197911 , 0.7802089 ],
       [0.79220624, 0.20779376],
       [0.55918267, 0.44081733],
       [0.2702991 , 0.7297009 ],
       [0.49544664, 0.50455336],
       [0.28744748, 0.71255252],
       [0.52867392, 0.47132608],
       [0.7737581 , 0.2262419 ],
       [0.52886078, 0.47113922],
       [0.46772936, 0.53227064],
       [0.22918432, 0.77081568],
       [0.20028972, 0.79971028],
       [0.67467385, 0.32532615],
       [0.52223755, 0.47776245],
       [0.5748822 , 0.4251178 ],
       [0.72399282, 0.27600718],
       [0.579609  , 0.420391  ],
       [0.67200189, 0.32799811],
       [0.23341184, 0.76658816],
       [0.22994551, 0.77005449],
       [0.60629879, 0.39370121],
       [0.73153303, 0.26846697],
       [0.61913465, 0.38086535],
       [0.

In [ ]:
X_recourse = X_test[model_trained.predict(X_test) == 0][:20]

In [7]:
np.dot(model_trained.coef_, X_test[0]) + model_trained.intercept_

array([-0.8460879])

In [10]:
1 / (1 + np.exp(-(np.dot(model_trained.coef_, X_test[0]) + model_trained.intercept_)))

array([0.30025415])

In [19]:
np.dot(np.concatenate((model_trained.coef_.squeeze(), model_trained.intercept_)), X_test[0])

ValueError: shapes (9,) and (8,) not aligned: 9 (dim 0) != 8 (dim 0)

In [12]:
model_trained.coef_

array([[-1.35294452, -0.4826626 ,  0.39909664,  0.853531  ,  1.11028091,
        -0.67962095, -0.40275798, -0.03171284]])

In [13]:
model_trained.coef_.shape

(1, 8)

In [14]:
X_test[0].shape

(8,)